version: '3.7'
services:

  postgres:
    build: ./docker
    hostname: postgres
    restart: on-failure
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - graphql

networks:
  graphql: